apiVersion: v1
kind: Secret
metadata:
  name:  ui-ingress
  namespace: dev
type: kubernetes.io/tls
data:
  tls.crt: 
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lKQU5lSzNyYXdn
    WW9VTUEwR0NTcUdTSWIzRFFFQkN3VUFNQmt4RnpBVkJnTlYKQkFNTURqTTBMakV3Tnk0eE16TXVN
    VGsxTUI0WERUSXdNREV4TURBNU5UUXpNRm9YRFRJeE1ERXdPVEE1TlRRegpNRm93R1RFWE1CVUdB
    MVVFQXd3T016UXVNVEEzTGpFek15NHhPVFV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBCkE0SUJE
    d0F3Z2dFS0FvSUJBUUNjZFF2UDBLRnZsd1lIY0R1ei9DWDBYaGRSN3VtOXEyTjFXYWJWK29ZeDYz
    eEYKYW1obXJYS1pqMUhXOXVXWEVjT1hSZ0xHQ2ViU01wWFR6QWdEVGltZzZaNmRrY0ZOdUlhVjM4
    S2xWYkQrdDAxWAovOHVkRDJEYVg1bU0raDJTNzF2KytFaExxRDA5bVFqS2JZZU4vb3diVWlqZlpL
    cEhab3JYZDYzbmduakJRbGYzCk1NU2hKUkJDZktVREY0eElpZHVJZURuUjhzaGdTeS9DZlRSbkV1
    bXFFNlVlZGozaGVKZjJUMGI5S1ROWU9oOUwKT0J4RU5JdlR6cDZvNVQvL3RySktQc3Q5S0hzSHdH
    ekxWd3RSaWVJbUNqTFpJSkw4dHFlV3ZKVVRlNWU0SE02QwpNdFJsWXNTYUZiNGViMGd1YVVmZFl1
    VEN3V1RSbExFN1pTTlBLZTN4QWdNQkFBR2pVREJPTUIwR0ExVWREZ1FXCkJCU2tsRHVLNDdZQ1R2
    YmtEUlBVS3I3aE9GSmh0ekFmQmdOVkhTTUVHREFXZ0JTa2xEdUs0N1lDVHZia0RSUFUKS3I3aE9G
    Smh0ekFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVBRSVk5ZXIx
    LwovL2V5Ny8xYVFwU2c0c3lCbzN4Qzc2VVdFSDBWeUhVZ2hEZDNnZmRuZ3pGOVgwWjREd1gwR2dk
    ck9oQTJrLzhyCmtMWGpxV3FZRE5UVXJnQXZCbFh4ZklzVTdkRjUyNE5XTVVYdmloaE5jMVFWeVhx
    Zy91TXQ2QVkwQ3h6cjNCdzkKSUhtMm1PUEd2T0xHU05uMHlRQkFOcWZnUjF6NlRUSEw4YlJaS3dI
    Qnd2aExaNWlwRDdDeDAyMU0xSk13OCswSgp3dnhDWEJuR3Q1MStaVGRlakk4REI5dlhMcnoxWlhs
    ektoOXFEME02NDJvRzNWc3A0WCtTR01QZjZUK2VHMkpVCmJGb1lIK1I4RWxmek5oRHZKUWhiUVRo
    TThFbmVHcE5UMVdKMHYrOGRGZ2FWaGE2VzRqei82WXN2VzlUSFlFRzMKUHEzOVdHU3dEOEs3Ci0t
    LS0tRU5EIENFUlRJRklDQVRFLS0tLS0K    
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
  QVNDQktZd2dnU2lBZ0VBQW9JQkFRQ2NkUXZQMEtGdmx3WUgKY0R1ei9DWDBYaGRSN3VtOXEyTjFX
  YWJWK29ZeDYzeEZhbWhtclhLWmoxSFc5dVdYRWNPWFJnTEdDZWJTTXBYVAp6QWdEVGltZzZaNmRr
  Y0ZOdUlhVjM4S2xWYkQrdDAxWC84dWREMkRhWDVtTStoMlM3MXYrK0VoTHFEMDltUWpLCmJZZU4v
  b3diVWlqZlpLcEhab3JYZDYzbmduakJRbGYzTU1TaEpSQkNmS1VERjR4SWlkdUllRG5SOHNoZ1N5
  L0MKZlRSbkV1bXFFNlVlZGozaGVKZjJUMGI5S1ROWU9oOUxPQnhFTkl2VHpwNm81VC8vdHJKS1Bz
  dDlLSHNId0d6TApWd3RSaWVJbUNqTFpJSkw4dHFlV3ZKVVRlNWU0SE02Q010UmxZc1NhRmI0ZWIw
  Z3VhVWZkWXVUQ3dXVFJsTEU3ClpTTlBLZTN4QWdNQkFBRUNnZ0VBTm9wZTZienk2ZkdkdW00WGdm
  QytVbWVTZlk5cGtDTDA4dTJqeVNnaUs3akoKZzNGS243Q0xLSmpia0xKVTZzcllnaDEzemcyWmwy
  RG05Z1JFTHRMS2xEdWNmWlZYNjM0Ti9LVWFONFNkeE0ybAplcTNERHlkVFBnemhmRkdjaWFKRFVh
  aS9teEEwK1FvbUZGc0dUQ3VXTDlmK1E1SFdBam51NEpucDE3Q1Y0OWh2ClFnbkNBSVllTkk2dUFL
  Zmo1djVlVHRCWkNzcG9WNjY4R3VhVno0QTJCSm4yS3RhSWFKaWdNRXlKOCtQTjg4SzgKUVgwelgr
  dEdkYTlzem5LT2ZwQ3dQOXFLbzcxcDVXTTYxeUJrdXMzZlNxVlNTUHRGOGNQNkpnTngrL2RBK3NV
  TApHYnN2OTlXYm5XSnJPczg0N3c2VVduUkJtT1UxQ0VOMmhBclIvcUtsSVFLQmdRREsxOGVEY1Fk
  M0FZaEpJVXppCkx6S3Z5dmRkZFJQWlZBUmdEc1hNeDltRTREamFiejNxZmlvL2FsbVkzQzl4SENr
  dUdSQnNKK0RZSXIveWgwemUKT2pGZmNHZEVVdWJLQWNkOHFoaW5Ma2t5cWFUTlgvejN3cnRCNmlu
  YS9mWGNQRVRPTzJkeFBnSmNydWFzVzZEQgp2SkRlOG95Z1Vtcks4WStrNll0U3loSGF0UUtCZ1FE
  RmRWNDZYek1hM3ZiTG9WeUg2WlJ0Z01qcDNTSjljaXJCClZ6Z0RXc0l5Qk1YdzR0alJuYktEa0xt
  ZHVCNGNhOHN5L2V2WFVUV2ZTWFB4SFEyTzMwZTA5YndScnhBcTNOQTIKL1R6cDVTVXZxNjBma2ZQ
  elNpK2RsdWdGM0t5bVNHTlV6VWQ2NENNU3luYXFWOXRUSHR6M1Fvdm9SYTVvYTR0cQpVUkxxeXFa
  L3pRS0JnRTREQVB0L1hBU2I5VU5TNkZQUkhTaFk0aHZ5YkNqWVZEcHhWQWQzRVNRMmJBY3VZMXl0
  Ckd5aDZpV3p0dWQxQm5HRGJTT0tmejZ5d2FLd285eG84dlVKY1k0cjJhMFpqdXNvcVRRTDNIVFc3
  NHVNTnVLZTkKSC9HdzBsb2o5QXU0cmltMjFRakxkWE1aM1NPS3RkL3MycmEwQi91YzF1K29TYnQr
  Q3BSVG5OeEZBb0dBWi9xeApQdzNJckpyQzNXSkFocldpMnJNWm1jVkFGMDBhWkt1WUxIUUxsU2xj
  VHNnMkl0UG5JRThDMzZJSUFURm1WSmpRCks1ZHhKRXNheWRwaHZGMnB0Z285R2hiVTdhMVAyOVVv
  MFlaQU9jVXVxbFJDWVZnc2tORFpwOVNYK2d4ZWVsYUwKRUpLZEJaVW1QZmQ3NEY1OVA1dUViekRh
  Y2RSSUd4bE1XK1dSSGZVQ2dZQnFZdy8zNklXa0lpc2RyRUYrSlRBdgpVU1JDaEViUnZuWDd1RFQr
  bmlkSmpmSTFlTDFhOW8wS1hzZVJOVGZQYVlrSjhZd2d4Q214cUM2RUY2SjViNEd6CnVMVGxkSTlz
  MUd6NU0ydDNzUUFRaXVQaHhFWngzdmlsWXZlQm1VRDZZd3oxUEpvZWxBQjg2c3VHc0NmZ0FyZXYK
  TkVwNUhmOUpTS05aZWxRVFhycmx0Zz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
  